//
//  RepetitionPasswordShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 08.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension RepetitionPasswordShowViewController: RepetitionPasswordShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension RepetitionPasswordShowInteractor: RepetitionPasswordShowViewControllerOutput {
}

extension RepetitionPasswordShowPresenter: RepetitionPasswordShowInteractorOutput {
}

class RepetitionPasswordShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = RepetitionPasswordShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: RepetitionPasswordShowViewController) {
        let router = RepetitionPasswordShowRouter()
        router.viewController = viewController
        
        let presenter = RepetitionPasswordShowPresenter()
        presenter.viewController = viewController
        
        let interactor = RepetitionPasswordShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
