//
//  RepetitionPasswordShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 08.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol RepetitionPasswordShowPresenterInput {
    func presentSomething(responseModel: RepetitionPasswordShowModels.Something.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol RepetitionPasswordShowPresenterOutput: class {
    func displaySomething(viewModel: RepetitionPasswordShowModels.Something.ViewModel)
}

class RepetitionPasswordShowPresenter: RepetitionPasswordShowPresenterInput {
    // MARK: - Properties
    weak var viewController: RepetitionPasswordShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(responseModel response: RepetitionPasswordShowModels.Something.ResponseModel) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = RepetitionPasswordShowModels.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
