//
//  RepetitionPasswordShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 08.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol RepetitionPasswordShowInteractorInput {
    func doSomething(requestModel: RepetitionPasswordShowModels.Something.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol RepetitionPasswordShowInteractorOutput {
    func presentSomething(responseModel: RepetitionPasswordShowModels.Something.ResponseModel)
}

class RepetitionPasswordShowInteractor: RepetitionPasswordShowInteractorInput {
    // MARK: - Properties
    var presenter: RepetitionPasswordShowInteractorOutput!
    var worker: RepetitionPasswordShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(requestModel: RepetitionPasswordShowModels.Something.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = RepetitionPasswordShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let responseModel = RepetitionPasswordShowModels.Something.ResponseModel()
        presenter.presentSomething(responseModel: responseModel)
    }
}
