//
//  OrganizationsShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 14.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol OrganizationsShowInteractorInput {
    func doSomething(requestModel: OrganizationsShowModels.Something.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol OrganizationsShowInteractorOutput {
    func presentSomething(responseModel: OrganizationsShowModels.Something.ResponseModel)
}

class OrganizationsShowInteractor: OrganizationsShowInteractorInput {
    // MARK: - Properties
    var presenter: OrganizationsShowInteractorOutput!
    var worker: OrganizationsShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(requestModel: OrganizationsShowModels.Something.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = OrganizationsShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let responseModel = OrganizationsShowModels.Something.ResponseModel()
        presenter.presentSomething(responseModel: responseModel)
    }
}
