//
//  SignInContainerShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 04.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension SignInContainerShowViewController: SignInContainerShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension SignInContainerShowInteractor: SignInContainerShowViewControllerOutput {
}

extension SignInContainerShowPresenter: SignInContainerShowInteractorOutput {
}

class SignInContainerShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = SignInContainerShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: SignInContainerShowViewController) {
        let router = SignInContainerShowRouter()
        router.viewController = viewController
        
        let presenter = SignInContainerShowPresenter()
        presenter.viewController = viewController
        
        let interactor = SignInContainerShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
