//
//  SignInContainerShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 04.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol SignInContainerShowInteractorInput {
    func doSomething(request: SignInContainerShow.Something.Request)
}

protocol SignInContainerShowInteractorOutput {
    func presentSomething(response: SignInContainerShow.Something.Response)
}

class SignInContainerShowInteractor: SignInContainerShowInteractorInput {
    // MARK: - Properties
    var output: SignInContainerShowInteractorOutput!
    var worker: SignInContainerShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(request: SignInContainerShow.Something.Request) {
        // NOTE: Create some Worker to do the work
        worker = SignInContainerShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let response = SignInContainerShow.Something.Response()
        output.presentSomething(response: response)
    }
}
