//
//  SignInContainerShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 04.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol SignInContainerShowPresenterInput {
    func presentSomething(response: SignInContainerShow.Something.Response)
}

protocol SignInContainerShowPresenterOutput: class {
    func displaySomething(viewModel: SignInContainerShow.Something.ViewModel)
}

class SignInContainerShowPresenter: SignInContainerShowPresenterInput {
    // MARK: - Properties
    weak var output: SignInContainerShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: SignInContainerShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = SignInContainerShow.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
