//
//  SignInContainerShowWorker.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 04.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class SignInContainerShowWorker {
    // MARK: - Custom Functions. Business Logic
    func doSomeWork() -> apiResponse {
        // NOTE: Do the work
        
        return (true, "asdasdashg")
    }
}
