//
//  ForgotPasswordShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension ForgotPasswordShowViewController: ForgotPasswordShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ForgotPasswordShowInteractor: ForgotPasswordShowViewControllerOutput {
}

extension ForgotPasswordShowPresenter: ForgotPasswordShowInteractorOutput {
}

class ForgotPasswordShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = ForgotPasswordShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: ForgotPasswordShowViewController) {
        let router = ForgotPasswordShowRouter()
        router.viewController = viewController
        
        let presenter = ForgotPasswordShowPresenter()
        presenter.viewController = viewController
        
        let interactor = ForgotPasswordShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
