//
//  ForgotPasswordShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol ForgotPasswordShowInteractorInput {
    func doSomething(request: ForgotPasswordShow.Something.Request)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol ForgotPasswordShowInteractorOutput {
    func presentSomething(response: ForgotPasswordShow.Something.Response)
}

class ForgotPasswordShowInteractor: ForgotPasswordShowInteractorInput {
    // MARK: - Properties
    var presenter: ForgotPasswordShowInteractorOutput!
    var worker: ForgotPasswordShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(request: ForgotPasswordShow.Something.Request) {
        // NOTE: Create some Worker to do the work
        worker = ForgotPasswordShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let response = ForgotPasswordShow.Something.Response()
        presenter.presentSomething(response: response)
    }
}
