//
//  ForgotPasswordShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol ForgotPasswordShowViewControllerInput {
    func displaySomething(viewModel: ForgotPasswordShow.Something.ViewModel)
}

protocol ForgotPasswordShowViewControllerOutput {
    func doSomething(request: ForgotPasswordShow.Something.Request)
}

class ForgotPasswordShowViewController: UIViewController, ForgotPasswordShowViewControllerInput {
    // MARK: - Properties
    var output: ForgotPasswordShowViewControllerOutput!
    var router: ForgotPasswordShowRouter!
    

    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        ForgotPasswordShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doInitialSetupOnLoad()
    }
    

    // MARK: - Custom Functions
    func doInitialSetupOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = ForgotPasswordShow.Something.Request()
        output.doSomething(request: request)

        // Setup App background color theme
        view.applyBackgroundTheme()
    }
    
    // Display logic
    func displaySomething(viewModel: ForgotPasswordShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
