//
//  NewsShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 14.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol NewsShowPresenterInput {
    func presentSomething(responseModel: NewsShowModels.Something.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol NewsShowPresenterOutput: class {
    func displaySomething(viewModel: NewsShowModels.Something.ViewModel)
}

class NewsShowPresenter: NewsShowPresenterInput {
    // MARK: - Properties
    weak var viewController: NewsShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(responseModel: NewsShowModels.Something.ResponseModel) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = NewsShowModels.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
