//
//  SlideMenuShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 13.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol SlideMenuShowInteractorInput {
    func doSomething(requestModel: SlideMenuShowModels.Something.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol SlideMenuShowInteractorOutput {
    func presentSomething(responseModel: SlideMenuShowModels.Something.ResponseModel)
}

class SlideMenuShowInteractor: SlideMenuShowInteractorInput {
    // MARK: - Properties
    var presenter: SlideMenuShowInteractorOutput!
    var worker: SlideMenuShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(requestModel: SlideMenuShowModels.Something.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = SlideMenuShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let responseModel = SlideMenuShowModels.Something.ResponseModel()
        presenter.presentSomething(responseModel: responseModel)
    }
}
