//
//  SlideMenuShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 13.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol SlideMenuShowViewControllerInput {
    func displaySomething(viewModel: SlideMenuShowModels.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol SlideMenuShowViewControllerOutput {
    func doSomething(requestModel: SlideMenuShowModels.Something.RequestModel)
}

class SlideMenuShowViewController: UIViewController {
    // MARK: - Properties
    var interactor: SlideMenuShowViewControllerOutput!
    var router: SlideMenuShowRouter!
    

    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        SlideMenuShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doSomethingOnLoad()
    }
    

    // MARK: - Custom Functions
    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let requestModel = SlideMenuShowModels.Something.RequestModel()
        interactor.doSomething(requestModel: requestModel)
    }
}


// MARK: - ForgotPasswordShowViewControllerInput
extension SlideMenuShowViewController: SlideMenuShowViewControllerInput {
    func displaySomething(viewModel: SlideMenuShowModels.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
