//
//  SlideMenuShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 13.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol SlideMenuShowPresenterInput {
    func presentSomething(responseModel: SlideMenuShowModels.Something.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol SlideMenuShowPresenterOutput: class {
    func displaySomething(viewModel: SlideMenuShowModels.Something.ViewModel)
}

class SlideMenuShowPresenter: SlideMenuShowPresenterInput {
    // MARK: - Properties
    weak var viewController: SlideMenuShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(responseModel: SlideMenuShowModels.Something.ResponseModel) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = SlideMenuShowModels.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
