//
//  SlideMenuShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 13.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension SlideMenuShowViewController: SlideMenuShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension SlideMenuShowInteractor: SlideMenuShowViewControllerOutput {
}

extension SlideMenuShowPresenter: SlideMenuShowInteractorOutput {
}

class SlideMenuShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = SlideMenuShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: SlideMenuShowViewController) {
        let router = SlideMenuShowRouter()
        router.viewController = viewController
        
        let presenter = SlideMenuShowPresenter()
        presenter.viewController = viewController
        
        let interactor = SlideMenuShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
