//
//  SlideMenuShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 13.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol SlideMenuShowInteractorInput {
    func didLoadData(withRequestModel requestModel: SlideMenuShowModels.DataSource.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol SlideMenuShowInteractorOutput {
    func didPrepareShowData(fromResponseModel responseModel: SlideMenuShowModels.DataSource.ResponseModel)
}

class SlideMenuShowInteractor: SlideMenuShowInteractorInput {
    // MARK: - Properties
    var presenter: SlideMenuShowInteractorOutput!
    var worker: SlideMenuShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func didLoadData(withRequestModel requestModel: SlideMenuShowModels.DataSource.RequestModel) {
        worker = SlideMenuShowWorker()
        let items = worker.createSlideMenu()
        
        // NOTE: Pass the result to the Presenter
        presenter.didPrepareShowData(fromResponseModel: SlideMenuShowModels.DataSource.ResponseModel(dataSource: items))
    }
}
