//
//  OrganizationsListShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension OrganizationsListShowViewController: OrganizationsListShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension OrganizationsListShowInteractor: OrganizationsListShowViewControllerOutput {
}

extension OrganizationsListShowPresenter: OrganizationsListShowInteractorOutput {
}

class OrganizationsListShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = OrganizationsListShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: OrganizationsListShowViewController) {
        let router = OrganizationsListShowRouter()
        router.viewController = viewController
        
        let presenter = OrganizationsListShowPresenter()
        presenter.output = viewController
        
        let interactor = OrganizationsListShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
