//
//  OrganizationsListShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OrganizationsListShowPresenterInput {
    func presentSomething(response: OrganizationsListShow.Something.Response)
}

protocol OrganizationsListShowPresenterOutput: class {
    func displaySomething(viewModel: OrganizationsListShow.Something.ViewModel)
}

class OrganizationsListShowPresenter: OrganizationsListShowPresenterInput {
    // MARK: - Properties
    weak var output: OrganizationsListShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: OrganizationsListShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = OrganizationsListShow.Something.ViewModel()
        output.displaySomething(viewModel: viewModel)
    }
}
