//
//  OrganizationsListShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol OrganizationsListShowViewControllerInput {
    func displaySomething(viewModel: OrganizationsListShow.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol OrganizationsListShowViewControllerOutput {
    func doSomething(request: OrganizationsListShow.Something.Request)
}

class OrganizationsListShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: OrganizationsListShowViewControllerOutput!
    var router: OrganizationsListShowRouter!
    
    @IBOutlet weak var customNavigationBarView: MainNavigationBarView!
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var emptyDataSourceView: UIView!

    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        OrganizationsListShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doInitialSetupOnLoad()
    }
    

    // MARK: - Custom Functions
    func doInitialSetupOnLoad() {
        // Delegates
        tableView.delegate = self
        tableView.dataSource = self
        
        // Handler menu bar button
        customNavigationBarView.handlerNavBarLeftButtonCompletion = { _ in
            self.print(object: "Menu item taped!!!")
        }
    }
    
    
    // MARK: - Actions
    @IBAction func handlerAddOrganizationButtonTap(_ sender: CustomButton) {
        router.navigateToOrganizationAddViewController()
    }
}


// MARK: - UITableViewDataSource
extension OrganizationsListShowViewController: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        let dataSourceCount = 0
        emptyDataSourceView.isHidden = (dataSourceCount == 0) ? false : true
        
        return dataSourceCount
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cellIdentifier = "OrganizationCell"
        var cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier) //as UITableViewCell
        
        if cell == nil {
            cell = UINib(nibName: cellIdentifier, bundle: nil).instantiate(withOwner: nil, options: nil).first as! UITableViewCell?
        }
        
        return cell!
    }
}


// MARK: - OrganizationsListShowViewControllerInput
extension OrganizationsListShowViewController: OrganizationsListShowViewControllerInput {
    func displaySomething(viewModel: OrganizationsListShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}


// MARK: - UITableViewDelegate
extension OrganizationsListShowViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 64.0
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
    }
    
    func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {
        
    }
}

