//
//  OrganizationsListShowRouter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol OrganizationsListShowRouterInput {
    func navigateToOrganizationAddViewController()
}

class OrganizationsListShowRouter: OrganizationsListShowRouterInput {
    // MARK: - Properties
    weak var viewController: OrganizationsListShowViewController!
    
    
    // MARK: - Custom Functions. Navigation
    func navigateToOrganizationAddViewController() {
        let storyboard = UIStoryboard(name: "OrganizationAdd", bundle: nil)
        let organizationAddController = storyboard.instantiateViewController(withIdentifier: "OrganizationAddVC") as! OrganizationAddViewController
        
        viewController.navigationController?.pushViewController(organizationAddController, animated: true)
    }
    
    // Communication
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        if segue.identifier == "ShowSomewhereScene" {
            passDataToSomewhereScene(segue: segue)
        }
    }
    
    // Transition
    func passDataToSomewhereScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router how to pass data to the next scene
        // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
        // someWhereViewController.output.name = viewController.output.name
    }
}
