//
//  SignUpShowWorker.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
//import Navajo_Swift
//
//enum PasswordStrengthLevel {
//    case Weak
//    case Reasonable
//    case Strong
//}

class SignUpShowWorker {
    // MARK: - Properties
//    private var validator = NJOPasswordValidator.standardValidator

    
    // MARK: - Custom Functions. Business Logic
//    func checkPasswordStrength(_ password: String) -> PasswordCheckResult {
//        let strengthLevelString = Navajo.localizedString(for: Navajo.strength(of: password))
//        var strengthLevel: PasswordStrengthLevel!
//        
//        switch strengthLevelString {
//        case "Very Weak", "Weak":
//            strengthLevel = .Weak
//            
//        case "Reasonable":
//            strengthLevel = .Reasonable
//            
//        case "Strong", "Very Strong":
//            strengthLevel = .Strong
//
//        default:
//            break
//        }
//
//        return PasswordCheckResult(strengthLevel: strengthLevel, isValid: checkPasswordValidation(password))
//    }
//    
//    private func checkPasswordValidation(_ password: String) -> Bool {
//        let lengthRule = NJOLengthRule(min: 8, max: 24)
//        validator = NJOPasswordValidator(rules: [lengthRule])
//        
//        if let failingRules = validator.validate(password) {
//            var errorMessages: [String] =   []
//            
//            failingRules.forEach { rule in
//                errorMessages.append(rule.localizedErrorDescription)
//            }
//            
//            return false
//        } else {
//            return true
//        }
//    }
    
    func didApplyREST() -> ResponseAPI {
        // NOTE: Do the work
        
        return (true, nil)
    }
}
