//
//  SignUpShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol SignUpShowViewControllerInput {
    func didShowPasswordTextFieldCheckResult(fromViewModel viewModel: SignUpShowModels.PasswordTextField.ViewModel)
    func didShowShowRegisterUserResult(fromViewModel viewModel: SignUpShowModels.User.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol SignUpShowViewControllerOutput {
    func didValidatePasswordTextFieldStrength(fromRequestModel requestModel: SignUpShowModels.PasswordTextField.RequestModel)
    func didRegisterUser(fromRequestModel requestModel: SignUpShowModels.User.RequestModel)
}

class SignUpShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: SignUpShowViewControllerOutput!
    var router: SignUpShowRouter!
    var handlerRegisterButtonCompletion: HandlerRegisterButtonCompletion?
    var handlerCancelButtonCompletion: HandlerCancelButtonCompletion?
    var passwordStrengthLevel: PasswordStrengthLevel = .None
    
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var passwordStrengthView: PasswordStrengthLevelView!
    @IBOutlet var textFieldsCollection: [CustomTextField]!
    @IBOutlet weak var emailErrorMessageView: ErrorMessageView!
    
    @IBOutlet weak var emailErrorMessageHeightConstraint: NSLayoutConstraint!
    @IBOutlet weak var emailErrorMessageViewTopConstraint: NSLayoutConstraint!
  
    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        SignUpShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doInitialSetupOnLoad()
    }
    

    // MARK: - Custom Functions
    func doInitialSetupOnLoad() {
        // UITextFields
        textFieldsArray = textFieldsCollection
        
        // Apply keyboard handler
        scrollViewBase = scrollView

        // Hide email error message view
        emailErrorMessageHeightConstraint.constant = Config.Constants.errorMessageViewHeight
        emailErrorMessageViewTopConstraint.constant = -Config.Constants.errorMessageViewHeight
    }
    
    
    // MARK: - Actions
    @IBAction func handlerRegisterButtonTap(_ sender: CustomButton) {
        let name = textFieldsCollection.first?.text
        let email = textFieldsCollection[1].text
        let password = textFieldsCollection.last?.text
        
        guard !((name?.isEmpty)!), !((password?.isEmpty)!), !((email?.isEmpty)!) else {
            // TODO: - ADD ALERT
            showAlertView(withTitle: "Info".localized(), andMessage: "All fields can be...".localized())
            
            return
        }
        
        if (textFieldsCollection[1].checkEmailValidation(email!)) {
            let requestModel = SignUpShowModels.User.RequestModel(name: name!, email: email!, password: password!)
            interactor.didRegisterUser(fromRequestModel: requestModel)
        } else {
            emailErrorMessageView.didShow(true, withConstraint: emailErrorMessageViewTopConstraint)
        }
    }
    
    @IBAction func handlerCancelButtonTap(_ sender: CustomButton) {
        handlerCancelButtonCompletion!()
    }
}


// MARK: - SignUpShowViewControllerInput
extension SignUpShowViewController: SignUpShowViewControllerInput {
    func didShowPasswordTextFieldCheckResult(fromViewModel: SignUpShowModels.PasswordTextField.ViewModel) {
//        passwordCheckResult?.strengthLevel = viewModel.strengthLevel
//        passwordCheckResult?.isValid = viewModel.isValid
//        passwordStrengthView.passwordStrengthLevel = viewModel.strengthLevel
    }
    
    func didShowShowRegisterUserResult(fromViewModel viewModel: SignUpShowModels.User.ViewModel) {
        guard viewModel.result.error == nil else {
            self.showAlertView(withTitle: "Error".localized(), andMessage: (viewModel.result.error?.description)!)
            
            return
        }
        
        Config.Constants.isUserGuest = false
        
        handlerRegisterButtonCompletion!()
    }
}


// MARK: - UITextFieldDelegate
extension SignUpShowViewController {
    override func textFieldDidEndEditing(_ textField: UITextField) {
        if (textField.tag == 1) {
            if ((textField as! CustomTextField).checkEmailValidation(textField.text!)) {
                emailErrorMessageView.didShow(false, withConstraint: emailErrorMessageViewTopConstraint)
            } else {
                emailErrorMessageView.didShow(true, withConstraint: emailErrorMessageViewTopConstraint)
            }
        }
    }
    
    override func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        if (textField.tag == 1) {
            emailErrorMessageView.didShow(false, withConstraint: emailErrorMessageViewTopConstraint)
        }
        
        if (textField.tag == 99) {
            passwordStrengthView.passwordStrengthLevel = (string.isEmpty && textField.text?.characters.count == 1) ? .None : (textField as! CustomTextField).checkPasswordStrength(textField.text! + string)
            passwordStrengthView.setNeedsDisplay()

            
            // Interactor output
//            passwordStrengthView.passwordString = (string.isEmpty && textField.text?.characters.count == 1) ? .Z : (textField.text! + string)
//            let passwordRequest = SignUpShowModels.PasswordTextField.Request(password: textField.text! + string)
//            interactor.validatePasswordTextFieldStrengthFrom(requestModel: passwordRequest)
        }
        
        return true
    }
    
    override func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if (textField.tag == 1) {
            if ((textField as! CustomTextField).checkEmailValidation(textField.text!)) {
                emailErrorMessageView.didShow(false, withConstraint: emailErrorMessageViewTopConstraint)
            } else {
                emailErrorMessageView.didShow(true, withConstraint: emailErrorMessageViewTopConstraint)
                
                return false
            }
        }
        
        if (textField.tag == 99) {
            if ((textField as! CustomTextField).checkPasswordValidation(textField.text!)) {
                textField.resignFirstResponder()
                
                return true
            } else {
                return false
            }
        } else {
            let indexCurrent = textFieldsArray.index(of: textField as! CustomTextField)!
            let indexNext = textFieldsArray.index(after: indexCurrent)
            
            textFieldsArray[indexNext].becomeFirstResponder()
        }

        return true
    }
    
    func textFieldShouldClear(_ textField: UITextField) -> Bool {
        if (textField.tag == 1) {
            emailErrorMessageView.didShow(false, withConstraint: emailErrorMessageViewTopConstraint)
        }
        
        if (textField.tag == 99) {
            passwordStrengthView.passwordStrengthLevel = .None
            passwordStrengthView.setNeedsDisplay()
        }
        
        return true
    }
}

