//
//  SignUpShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocol for current Presenter
protocol SignUpShowPresenterInput {
    func preparePasswordTextFieldResultForShowFrom(responseModel: SignUpShowModels.PasswordTextField.Response)
}

// MARK: - Output protocol for ViewController
protocol SignUpShowPresenterOutput: class {
    func showPasswordTextFieldCheckResult(viewModel: SignUpShowModels.PasswordTextField.ViewModel)
}

class SignUpShowPresenter: SignUpShowPresenterInput {
    // MARK: - Properties
    weak var viewController: SignUpShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func preparePasswordTextFieldResultForShowFrom(responseModel: SignUpShowModels.PasswordTextField.Response) {
        let viewModel = SignUpShowModels.PasswordTextField.ViewModel(password: responseModel.password, isValid: responseModel.isValid)
        
        viewController.showPasswordTextFieldCheckResult(viewModel: viewModel)
    }
}
