//
//  SignUpShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol SignUpShowPresenterInput {
    func didPrepareShowPasswordTextFieldResult(fromResponseModel responseModel: SignUpShowModels.PasswordTextField.ResponseModel)
    func didPrepareShowRegisterUserResult(fromResponseModel responseModel: SignUpShowModels.User.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol SignUpShowPresenterOutput: class {
    func didShowPasswordTextFieldCheckResult(fromViewModel viewModel: SignUpShowModels.PasswordTextField.ViewModel)
    func didShowShowRegisterUserResult(fromViewModel viewModel: SignUpShowModels.User.ViewModel)
}

class SignUpShowPresenter: SignUpShowPresenterInput {
    // MARK: - Properties
    weak var viewController: SignUpShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func didPrepareShowPasswordTextFieldResult(fromResponseModel responseModel: SignUpShowModels.PasswordTextField.ResponseModel) {
        let viewModel = SignUpShowModels.PasswordTextField.ViewModel(strengthLevel: responseModel.strengthLevel, isValid: responseModel.isValid)
        
        viewController.didShowPasswordTextFieldCheckResult(fromViewModel: viewModel)
    }
    
    func didPrepareShowRegisterUserResult(fromResponseModel responseModel: SignUpShowModels.User.ResponseModel) {
        let viewModel = SignUpShowModels.User.ViewModel(result: responseModel.result)
        
        viewController.didShowShowRegisterUserResult(fromViewModel: viewModel)

    }
}
