//
//  SignUpShowWorker.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import Navajo_Swift

class SignUpShowWorker {
    // MARK: - Properties
    private var validator = NJOPasswordValidator.standardValidator

    
    // MARK: - Custom Functions. Business Logic
    func checkPasswordStrength(_ password: String) -> PasswordStrengthResult {
        return (Navajo.localizedString(for: Navajo.strength(of: password)), checkPasswordValidation(password))
    }
    
    private func checkPasswordValidation(_ password: String) -> Bool {
        let lengthRule = NJOLengthRule(min: 8, max: 24)
        validator = NJOPasswordValidator(rules: [lengthRule])
        
        if let failingRules = validator.validate(password) {
            var errorMessages: [String] =   []
            
            failingRules.forEach { rule in
                errorMessages.append(rule.localizedErrorDescription)
            }
            
            return false
        } else {
            return true
        }
    }
}
