//
//  SignUpShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input & Output protocols
protocol SignUpShowPresenterInput {
    func presentUpdatedTextField(response: SignUpShowModels.UpdateTextField.Response)

    // DEMO
    func presentSomething(response: SignUpShowModels.Something.Response)
}

protocol SignUpShowPresenterOutput: class {
    func updateTextField(model: SignUpShowModels.UpdateTextField.ViewModel)
   
    // DEMO
    func displaySomething(viewModel: SignUpShowModels.Something.ViewModel)
}

class SignUpShowPresenter: SignUpShowPresenterInput {
    // MARK: - Properties
    weak var output: SignUpShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentUpdatedTextField(response: SignUpShowModels.UpdateTextField.Response) {
        let model = SignUpShowModels.UpdateTextField.ViewModel(text: response.text)
        
        output.updateTextField(model: model)
    }

    func presentSomething(response: SignUpShowModels.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = SignUpShowModels.Something.ViewModel()
        
        output.displaySomething(viewModel: viewModel)
    }
}
