//
//  OrganizationMapShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 10.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension OrganizationMapShowViewController: OrganizationMapShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension OrganizationMapShowInteractor: OrganizationMapShowViewControllerOutput {
}

extension OrganizationMapShowPresenter: OrganizationMapShowInteractorOutput {
}

class OrganizationMapShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = OrganizationMapShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: OrganizationMapShowViewController) {
        let router = OrganizationMapShowRouter()
        router.viewController = viewController
        
        let presenter = OrganizationMapShowPresenter()
        presenter.viewController = viewController
        
        let interactor = OrganizationMapShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
