//
//  OrganizationMapShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 10.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol OrganizationMapShowInteractorInput {
    func doSomething(requestModel: OrganizationMapShowModels.Something.RequestModel)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol OrganizationMapShowInteractorOutput {
    func presentSomething(responseModel: OrganizationMapShowModels.Something.ResponseModel)
}

class OrganizationMapShowInteractor: OrganizationMapShowInteractorInput {
    // MARK: - Properties
    var presenter: OrganizationMapShowInteractorOutput!
    var worker: OrganizationMapShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(requestModel: OrganizationMapShowModels.Something.RequestModel) {
        // NOTE: Create some Worker to do the work
        worker = OrganizationMapShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let responseModel = OrganizationMapShowModels.Something.ResponseModel()
        presenter.presentSomething(responseModel: responseModel)
    }
}
