//
//  OrganizationMapShowModels.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 10.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit

// MARK: - Data models
struct OrganizationMapShowModels {
    struct Forward {
        struct RequestModel {
            let address: String?
        }
        
        struct ResponseModel {
//            let placemark: CLPlacemark
            //            let address: String?
            //            let coordinate: CLLocationCoordinate2D?
            //            let info: String?
        }
        
        struct ViewModel {
            //            let address: String
            //            let coordinate: CLLocationCoordinate2D
        }
    }

    struct Reverse {
        struct RequestModel {
            let address: String?
        }
        
        struct ResponseModel {
            //            let placemark: CLPlacemark
            //            let address: String?
            //            let coordinate: CLLocationCoordinate2D?
            //            let info: String?
        }
        
        struct ViewModel {
            //            let address: String
            //            let coordinate: CLLocationCoordinate2D
        }
    }

    struct Common {
        struct RequestModel {
        }
        
        struct ResponseModel {
        }
        
        struct ViewModel {
        }
    }
}
