//
//  OrganizationMapShowModels.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 10.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import MapKit

// MARK: - Data models
struct OrganizationMapShowModels {
    struct Location {
        struct RequestModel {
            let locationManager: LocationManager
            let searchLocation: SearchLocation?
        }
        
        struct ResponseModel {
            let placemark: CLPlacemark?
        }
        
        struct ViewModel {
            let resultLocation: ResultLocation?
        }
    }
}
