//
//  MainShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension MainShowViewController: MainShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension MainShowInteractor: MainShowViewControllerOutput {
}

extension MainShowPresenter: MainShowInteractorOutput {
}

class MainShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = MainShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: MainShowViewController) {
        let router = MainShowRouter()
        router.viewController = viewController
        
        let presenter = MainShowPresenter()
        presenter.output = viewController
        
        let interactor = MainShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
