//
//  MainShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol MainShowViewControllerInput {
    func displaySomething(viewModel: MainShow.Something.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol MainShowViewControllerOutput {
    func doSomething(request: MainShow.Something.Request)
}

class MainShowViewController: UIViewController, MainShowViewControllerInput {
    // MARK: - Properties
    var interactor: MainShowViewControllerOutput!
    var router: MainShowRouter!
    
    @IBOutlet weak var guestView: UIView!
    @IBOutlet weak var userView: UIView!

    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        MainShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doInitialSetupOnLoad()
    }
    

    // MARK: - Custom Functions
    func showBackground() {        
        switch Config.Constants.isUserGuest {
        case true:
            userView.isHidden = true
            guestView.applyBackgroundTheme()
            
        default:
            guestView.isHidden = true
            userView.applyBackgroundTheme()
        }
    }
    
    func doInitialSetupOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = MainShow.Something.Request()
        interactor.doSomething(request: request)
        
        showBackground()
    }
    
    // Display logic
    func displaySomething(viewModel: MainShow.Something.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}
