//
//  MainShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 02.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol MainShowPresenterInput {
    func presentSomething(response: MainShow.Something.Response)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol MainShowPresenterOutput: class {
    func displaySomething(viewModel: MainShow.Something.ViewModel)
}

class MainShowPresenter: MainShowPresenterInput {
    // MARK: - Properties
    weak var viewController: MainShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: MainShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = MainShow.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
