//
//  SignInShowModels.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Data models
struct SignInShowModels {
    struct User {
        struct RequestModel {
            let name: String
            let password: String
        }
        
        struct ResponseModel {
            let result: apiResponse
        }
        
        struct ViewModel {
            let result: apiResponse
        }
    }
}
