//
//  SignInShowViewController.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import SwiftyVK
import FBSDKLoginKit
import GoogleSignIn

// MARK: - Input protocols for current ViewController component VIP-cicle
protocol SignInShowViewControllerInput {
    func displaySomething(viewModel: SignInShowModels.User.ViewModel)
}

// MARK: - Output protocols for Interactor component VIP-cicle
protocol SignInShowViewControllerOutput {
    func didUserSignIn(requestModel: SignInShowModels.User.RequestModel)
}

enum AnimationDirection {
    case FromLeftToRight
    case FromRightToLeft
}

class SignInShowViewController: BaseViewController {
    // MARK: - Properties
    var interactor: SignInShowViewControllerOutput!
    var router: SignInShowRouter!
    var animationDirection: AnimationDirection?
    
    // Managers
    var socialNetworkManager: SocialNetworkManager?
    
    // Container childVC
    var signUpShowVC: SignUpShowViewController?
    var signInContainerShowVC: SignInContainerShowViewController?
    var forgotPasswordShowVC: ForgotPasswordShowViewController?
    var enterCodeShowViewController: EnterCodeShowViewController?
    var repetitionPasswordShowViewController: RepetitionPasswordShowViewController?
    
    var activeViewController: BaseViewController? {
        didSet {
            guard oldValue != nil else {
                router.updateActiveViewController()
                
                return
            }
            
            animationDirection = ((oldValue?.view.tag)! < (activeViewController?.view.tag)!) ? .FromRightToLeft : .FromLeftToRight
            router.removeInactiveViewController(inactiveViewController: oldValue)
        }
    }
    
    // Social network buttons
    @IBOutlet weak var vkontakteButton: CustomButton!
    @IBOutlet weak var googleButton: CustomButton!
    @IBOutlet weak var facebookButton: CustomButton!


    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var logoBackgroundView: UIView!
    @IBOutlet weak var containerStackView: UIStackView!
    @IBOutlet weak var socialButtonsView: UIView!

    
    // MARK: - Class initialization
    override func awakeFromNib() {
        super.awakeFromNib()
        
        SignInShowConfigurator.sharedInstance.configure(viewController: self)
    }
    

    // MARK: - Class Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doInitialSetupOnLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        
        view.applyBackgroundTheme()
        socialButtonsView.applyBackgroundTheme()
        logoBackgroundView.applyBackgroundTheme()
    }


    // MARK: - Custom Functions
    func doInitialSetupOnLoad() {
//        let requestModel = SignInShowModels.User.RequestModel()
//        interactor.doSomething(request: requestModel)
        
        // Hide navigation bar
        hideNavigationBar()
        
        // Apply Container childVC
        (Config.Constants.isUserGuest) ? router.navigateBetweenContainerSubviews() : router.navigateAuthorizedUser(duringStartApp: true)
        
        // Setup App background color theme
        logoBackgroundView.applyBackgroundTheme()
    }
    
    
    // MARK: - Actions
    @IBAction func handlerSocialNetworkButtonTap(_ sender: CustomButton) {
        print(object: "\(type(of: self)): \(#function) run. Vk button tap.")
       
        // Only for Google
        if (sender.tag == 1) {
            GIDSignIn.sharedInstance().uiDelegate = self
        }
        
        if (sender.tag == 2) {
            let facebook = FBSDKLoginManager()
            
            facebook.logIn(withReadPermissions: ["public_profile", "email"], from: self) { (result, error) in
                guard result?.token != nil else {
                    return
                }
                
                let fbToken = result!.token.tokenString
                let fbUserID = result!.token.userID
                
                //            let fbUserEmail = result!.token.
                //            let strFirstName: String = (result.objectForKey("first_name") as? String)!
                //            let strLastName: String = (result.objectForKey("last_name") as? String)!
                //            let strPictureURL: String = (result.objectForKey("picture")?.objectForKey("data")?.objectForKey("url") as? String)!
                
                Config.Constants.isUserGuest = false
                
                self.router.navigateAuthorizedUser(duringStartApp: false)
            }
        } else {
            socialNetworkManager = SocialNetworkManager(withNetwork: sender.tag)
            socialNetworkManager!.didAuthorizeUser()
            
            // Handler Auth successfull request
            socialNetworkManager?.handlerSendButtonCompletion = { _ in
                Config.Constants.isUserGuest = false
                
                self.router.navigateAuthorizedUser(duringStartApp: false)
            }
        }
    }
    
    
    // MARK: - Gesture
    @IBAction func handlerTapGestureRecognizer(_ sender: UITapGestureRecognizer) {
        view.endEditing(true)
    }
}


// MARK: - SignInShowViewControllerInput
extension SignInShowViewController: SignInShowViewControllerInput {
    func displaySomething(viewModel: SignInShowModels.User.ViewModel) {
        // NOTE: Display the result from the Presenter
        // nameTextField.text = viewModel.name
    }
}


// MARK: - GIDSignInUIDelegate
extension SignInShowViewController: GIDSignInUIDelegate {
    // Stop the UIActivityIndicatorView animation that was started when the user pressed the Sign In button
    private func signInWillDispatch(signIn: GIDSignIn!, error: NSError!) {
        print(object: #function)
    }
    
    // Present a view that prompts the user to sign in with Google
    private func signIn(signIn: GIDSignIn!, presentViewController viewController: UIViewController!) {
        print(object: #function)
        
        self.present(viewController, animated: true, completion: nil)
    }
    
    // Dismiss the "Sign in with Google" view
    private func signIn(signIn: GIDSignIn!, dismissViewController viewController: UIViewController!) {
        print(object: #function)
        
        self.dismiss(animated: true, completion: nil)
    }
}

