//
//  SignInShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol SignInShowInteractorInput {
    func doSomething(request: SignInShow.Something.Request)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol SignInShowInteractorOutput {
    func presentSomething(response: SignInShow.Something.Response)
}

class SignInShowInteractor: SignInShowInteractorInput {
    // MARK: - Properties
    var presenter: SignInShowInteractorOutput!
    var worker: SignInShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(request: SignInShow.Something.Request) {
        // NOTE: Create some Worker to do the work
        worker = SignInShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let response = SignInShow.Something.Response()
        presenter.presentSomething(response: response)
    }
}
