//
//  SignInShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 03.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension SignInShowViewController: SignInShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension SignInShowInteractor: SignInShowViewControllerOutput {
}

extension SignInShowPresenter: SignInShowInteractorOutput {
}

class SignInShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = SignInShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: SignInShowViewController) {
        let router = SignInShowRouter()
        router.viewController = viewController
        
        let presenter = SignInShowPresenter()
        presenter.output = viewController
        
        let interactor = SignInShowInteractor()
        interactor.output = presenter
        
        viewController.output = interactor
        viewController.router = router
    }
}
