//
//  OrganizationAddConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 09.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension OrganizationAddViewController: OrganizationAddPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension OrganizationAddInteractor: OrganizationAddViewControllerOutput {
}

extension OrganizationAddPresenter: OrganizationAddInteractorOutput {
}

class OrganizationAddConfigurator {
    // MARK: - Properties
    static let sharedInstance = OrganizationAddConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: OrganizationAddViewController) {
        let router = OrganizationAddRouter()
        router.viewController = viewController
        
        let presenter = OrganizationAddPresenter()
        presenter.viewController = viewController
        
        let interactor = OrganizationAddInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
