//
//  EnterCodeShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 07.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol EnterCodeShowPresenterInput {
    func presentSomething(response: EnterCodeShow.Something.Response)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol EnterCodeShowPresenterOutput: class {
    func displaySomething(viewModel: EnterCodeShow.Something.ViewModel)
}

class EnterCodeShowPresenter: EnterCodeShowPresenterInput {
    // MARK: - Properties
    weak var viewController: EnterCodeShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func presentSomething(response: EnterCodeShow.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = EnterCodeShow.Something.ViewModel()
        viewController.displaySomething(viewModel: viewModel)
    }
}
