//
//  EnterCodeShowConfigurator.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 07.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension EnterCodeShowViewController: EnterCodeShowPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension EnterCodeShowInteractor: EnterCodeShowViewControllerOutput {
}

extension EnterCodeShowPresenter: EnterCodeShowInteractorOutput {
}

class EnterCodeShowConfigurator {
    // MARK: - Properties
    static let sharedInstance = EnterCodeShowConfigurator()
    
    
    // MARK: - Class initialization
    private init() {}
    

    // MARK: - Custom Functions
    func configure(viewController: EnterCodeShowViewController) {
        let router = EnterCodeShowRouter()
        router.viewController = viewController
        
        let presenter = EnterCodeShowPresenter()
        presenter.viewController = viewController
        
        let interactor = EnterCodeShowInteractor()
        interactor.presenter = presenter
        
        viewController.interactor = interactor
        viewController.router = router
    }
}
