//
//  EnterCodeShowInteractor.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 07.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Interactor component VIP-cicle
protocol EnterCodeShowInteractorInput {
    func doSomething(request: EnterCodeShow.Something.Request)
}

// MARK: - Output protocols for Presenter component VIP-cicle
protocol EnterCodeShowInteractorOutput {
    func presentSomething(response: EnterCodeShow.Something.Response)
}

class EnterCodeShowInteractor: EnterCodeShowInteractorInput {
    // MARK: - Properties
    var presenter: EnterCodeShowInteractorOutput!
    var worker: EnterCodeShowWorker!
    
    
    // MARK: - Custom Functions. Business logic
    func doSomething(request: EnterCodeShow.Something.Request) {
        // NOTE: Create some Worker to do the work
        worker = EnterCodeShowWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        let response = EnterCodeShow.Something.Response()
        presenter.presentSomething(response: response)
    }
}
