//
//  EnterCodeShowPresenter.swift
//  OmnieCommerceAdmin
//
//  Created by msm72 on 07.02.17.
//  Copyright (c) 2017 Omniesoft. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Input protocols for current Presenter component VIP-cicle
protocol EnterCodeShowPresenterInput {
    func prepareValidationResultForShowFrom(responseModel: EnterCodeShowModels.Code.ResponseModel)
}

// MARK: - Output protocols for ViewController component VIP-cicle
protocol EnterCodeShowPresenterOutput: class {
    func returnValidationResult(viewModel: EnterCodeShowModels.Code.ViewModel)
}

class EnterCodeShowPresenter: EnterCodeShowPresenterInput {
    // MARK: - Properties
    weak var viewController: EnterCodeShowPresenterOutput!
    
    
    // MARK: - Custom Functions. Presentation logic
    func prepareValidationResultForShowFrom(responseModel: EnterCodeShowModels.Code.ResponseModel) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        let viewModel = EnterCodeShowModels.Code.ViewModel(isValueValid: responseModel.isValueValid)
        
        viewController.returnValidationResult(viewModel: viewModel)
    }
}
